from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.proxy import Proxy, ProxyType
import undetected_chromedriver.v2 as uc
import mysql.connector
import time

PROXY = "209.127.191.180:9279" 
chrome_options = uc.ChromeOptions()
chrome_options.add_argument('--proxy-server=%s' % PROXY)
browser = uc.Chrome(options=chrome_options)


mydb = mysql.connector.connect(
  host="192.168.0.48",
  user="username",
  password="password",
  database="schema"
)

with browser:
 browser.get('https://pastebin.com/')
 browser.find_element(By.NAME, "PostForm[text]").send_keys('Molza cute')
 browser.find_element(By.ID,"postform-name").send_keys('Fucker Tarlson');
 browser.find_element(By.XPATH, "/html/body/div[1]/div[2]/div[1]/div[2]/div/form/div[5]/div[1]/div[5]/div[1]/label").click() #Check password checkbox
 obj= browser.find_element(By.ID,"postform-password")
 password = obj.get_attribute("value") #Get password that was generated by pastebin
 browser.find_element(By.XPATH,"/html/body/div[1]/div[2]/div[1]/div[2]/div/form/div[5]/div[1]/div[8]/button").click() #Submit the form
 time.sleep(1.2)
 WebDriverWait(browser, 8.8).until(EC.presence_of_element_located((By.CLASS_NAME, 'content__title'))) # Wait for page to load
 url = browser.current_url
 mycursor = mydb.cursor()
 sql = "INSERT INTO data (password,url) VALUES (%s, %s)"
 val = (password,url)
 mycursor.execute(sql, val)
 mydb.commit()
 print("Logged")
 browser.close